apiVersion: v1
kind: Service
metadata:
  name: ollama
  namespace: inference
  labels: 
    app: ollama
spec:
  selector:
    app: ollama
  ports:
    - name: inference
      port: 11435
      targetPort: 11435