repositories:
  - name: argo
    url: https://argoproj.github.io/argo-helm

releases:
  # Argocd
  - name: argocd
    namespace: argocd
    chart: argo/argo-cd
    version: 9.4.17
    createNamespace: false
    installed: true
    wait: true
    values:
      - values/argocd.yaml
