apiVersion: v1
kind: Namespace
metadata:
  name:  linkerd
  labels:
    linkerd.io/is-control-plane: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name:  cert-manager
  annotations: 
    linkerd.io/inject: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name:  inference
  annotations: 
    linkerd.io/inject: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name:  monitoring
  annotations: 
    linkerd.io/inject: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name:  gateway-api
  annotations: 
    linkerd.io/inject: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name:  keda
  annotations: 
    linkerd.io/inject: enabled
