apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manifests
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/Ofor-David/gke-llm-platform.git
    targetRevision: main
    path: k8s/platform/cert-manager
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=false