apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: linkerd-control-plane
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: https://helm.linkerd.io/edge
    chart: linkerd-control-plane
    targetRevision: "2026.2.1"
    helm:
      valuesObject:
        identity:
          externalCA: true
          issuer:
            scheme: kubernetes.io/tls
  destination:
    server: https://kubernetes.default.svc
    namespace: linkerd
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=false
