image:
  repository: europe-west4-docker.pkg.dev/project-id/container-images/auth-service
  tag: "d33e6358b6fac3ba0280136a346708027315222b"
  pullPolicy: IfNotPresent

ratelimiterUrl: "http://rate-limiter.ratelimit.svc.cluster.local:8001"

# Ollama API key secret name
ollamaApiKeySecretRef: "ollama-api-key"
allowedIPs: ""  # comma separated, empty means all IPs allowed

resources:
  requests:
    memory: "128Mi"
    cpu: "100m"
  limits:
    memory: "256Mi"
    cpu: "200m"

replicaCount: 1