apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-admin-password
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-manager
    kind: ClusterSecretStore
  target:
    name: grafana-admin-password # Name of the K8s secret to create
  data:
    - secretKey: user        # Key name in the K8s secret
      remoteRef:
        key: grafana-admin-password # GCP Secret name
        property: user           # Key inside the GCP secret
    - secretKey: password    # Key name in the K8s secret
      remoteRef:
        key: grafana-admin-password # GCP Secret name
        property: password       # Key inside the GCP secret

---

apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ollama-api-key
  namespace: auth
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-manager
    kind: ClusterSecretStore
  target:
    name: ollama-api-key
  data:
    - secretKey: api-key
      remoteRef:
        key: ollama-api-key
        property: api-key