apiVersion: v1
kind: ServiceAccount
metadata:
  name: secrets-ksa
  namespace: cert-manager
  annotations:
    iam.gke.io/gcp-service-account: secrets-sa@project-id.iam.gserviceaccount.com

---

apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: gcp-secret-manager
spec:
  provider:
    gcpsm:
      projectID: project-id
      auth:
        workloadIdentity:
          serviceAccountRef:
            name: secrets-ksa
            namespace: cert-manager
