image:
  repository: europe-west4-docker.pkg.dev/seventh-azimuth-488017-b3/container-images/rate-limiter
  tag: "694a52ff87dc5d2cd5d94719295fcfb0c3a7d13e"
  pullPolicy: IfNotPresent

ollamaUrl: "http://ollama.inference.svc.cluster.local:11435"
redisUrl: "redis://redis.ratelimit.svc.cluster.local:6379"
rateLimit: "10"
windowSeconds: "60"

resources:
  requests:
    memory: "128Mi"
    cpu: "100m"
  limits:
    memory: "256Mi"
    cpu: "200m"

replicaCount: 1

redis:
  image: redis:8.6.1-alpine
  resources:
    requests:
      memory: "64Mi"
      cpu: "50m"
    limits:
      memory: "128Mi"
      cpu: "100m"